"""The ONE examiner-relationship input contract for the study layer.

    meoclass1/oral-intelligence/examiner-audit/EXAMINER_INDEX_SNAPSHOT.json
            |  (written by tools/oral/build_examiner_index.py, release gate
            |   examiner_check + validate_examiner_index)
            v
    examiner_source.load()  ->  build_study_spine / build_coverage_matrix /
                                export_roadmap_xlsx / build_topic_pages

WHY THE SNAPSHOT AND NOT CURRENT_EXAMINER_RELATIONSHIPS.jsonl
-------------------------------------------------------------
CURRENT_EXAMINER_RELATIONSHIPS.jsonl is the Phase-2 recovery ledger: written
once by tools/oral/recover_relationships.py from the hand-uploaded examiner
index (2026-08-23, 721-question corpus). It is an UPSTREAM input of
build_examiner_index.py, which resolves it together with QB card attributions
(QCARD), Release A (RELEASE_A) and the CE-tip review (CE_TIP_REVIEW) into the
published snapshot. Re-running the recovery against today's generated index
would be circular, so the ledger is not regenerated; the study layer reads the
resolved snapshot the product itself renders from.

Reconciled 2026-10-08 (docs/study/ORAL_EXAMINER_SOURCE_RECONCILIATION_20261008.md):
every one of the ledger's 860 pairs is present in the snapshot, the snapshot
adds 98 provenance-carrying pairs, and no pair is dropped.

TIERS ARE NEVER COLLAPSED
-------------------------
Every row keeps the tier build_examiner_index resolved for it (confirmed,
reported, ce_tip, header, inferred) and its sources. Labels and meanings come
from tools/oral/examiner_index_config.json, the same vocabulary the Examiner
Index prints, so a candidate reads one meaning for one word on both surfaces.
`any tier` is a declared denominator, never a silent one.

Fails closed: a snapshot that does not cover the current canonical corpus, or
a tier without a policy entry, raises -- it is not skipped.
"""
import collections, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

SNAPSHOT_REL = ('meoclass1/oral-intelligence/examiner-audit/'
                'EXAMINER_INDEX_SNAPSHOT.json')
SNAPSHOT = os.path.join(ROOT, *SNAPSHOT_REL.split('/'))
CONFIG = os.path.join(ROOT, 'tools', 'oral', 'examiner_index_config.json')
QB_INDEX = os.path.join(ROOT, 'meoclass1', 'qb_content_index.json')

CONTRACT = ('EXAMINER_INDEX_SNAPSHOT.json rows (canonical_question_id, '
            'examiner, tier, sources); generated by '
            'tools/oral/build_examiner_index.py')


class ExaminerSourceError(Exception):
    pass


def tier_policy():
    """tier -> {label, rank, meaning}, strongest first."""
    tiers = json.load(open(CONFIG, encoding='utf-8'))['tiers']
    return dict(sorted(tiers.items(), key=lambda kv: -kv[1]['rank']))


def load():
    """Validated snapshot rows. Raises ExaminerSourceError on any doubt."""
    snap = json.load(open(SNAPSHOT, encoding='utf-8'))
    rows = snap['rows']
    policy = tier_policy()
    idx = json.load(open(QB_INDEX, encoding='utf-8'))
    live = {q['id'] for f in idx['files'].values() for q in f['questions']}
    if snap['totals'].get('canonical_questions') != idx['total_questions']:
        raise ExaminerSourceError(
            f"snapshot built over {snap['totals'].get('canonical_questions')} "
            f"questions, corpus has {idx['total_questions']}: rebuild "
            f"tools/oral/build_examiner_index.py first")
    seen = set()
    for r in rows:
        key = (r['canonical_question_id'], r['examiner'])
        if r['canonical_question_id'] not in live:
            raise ExaminerSourceError(f'{key} names no live canonical question')
        if r['tier'] not in policy:
            raise ExaminerSourceError(f'{key} tier {r["tier"]!r} has no policy')
        if key in seen:
            raise ExaminerSourceError(f'{key} appears twice')
        seen.add(key)
    return rows


def by_question(rows=None):
    """canonical_question_id -> {examiner: tier}."""
    out = collections.defaultdict(dict)
    for r in (load() if rows is None else rows):
        out[r['canonical_question_id']][r['examiner']] = r['tier']
    return out


def strongest_tier(tiers, policy=None):
    """The highest-ranked tier among `tiers` (an iterable of tier literals)."""
    policy = policy or tier_policy()
    return max(tiers, key=lambda t: policy[t]['rank'])
