// Expansion Manager (Stage 3, item 1) + Amendment Tracker (item 3) +
// Repository Metrics (item 7) + a rendered Roadmap summary (item 5). Purely
// a read view over index/expansion-manager.json, index/amendment-tracker.json,
// and index/metrics-history.json — all three are generated by build scripts
// that either merge computed facts with the hand-curated
// repository/expansion-plan.json, or reconstruct real history from git.
window.RulesExpansion = (function () {
  const DB = window.RulesDB;
  const R = window.RulesRender;

  const PRIORITY_CLASS = { high: 'pri-high', medium: 'pri-medium', low: 'pri-low', 'long-term': 'pri-longterm' };
  function priorityBadge(p) { return `<span class="priority-badge ${PRIORITY_CLASS[p] || ''}">${R.esc(p || 'unset')}</span>`; }
  function stageBadge(stage) {
    const cls = stage === 'completed' ? 'ed-pass' : stage === 'in-progress' ? 'ed-tag' : 'muted';
    return `<span class="ed-tag ${cls}">${R.esc(stage)}</span>`;
  }

  // ---------- Expansion Manager ----------
  function renderManager() {
    const container = document.getElementById('expansion-manager-content');
    if (!container) return;
    const em = DB.getExpansionManager();
    if (!em) { container.innerHTML = '<p class="muted">index/expansion-manager.json not found — run repository/build/expansion-manager.js.</p>'; return; }

    container.innerHTML = `
      <div class="stats-grid">
        ${['packagesInProgressCount', 'packagesPlannedCount'].map((k) => `<div class="stat-card"><div class="stat-value">${em[k]}</div><div class="stat-label">${k.replace(/([A-Z])/g, ' $1').replace('Count', '').trim()}</div></div>`).join('')}
        <div class="stat-card"><div class="stat-value">${em.packagesCompleted.length}</div><div class="stat-label">Packages fully complete (100%)</div></div>
        ${Object.keys(em.priorityCounts).map((p) => `<div class="stat-card"><div class="stat-value">${em.priorityCounts[p]}</div><div class="stat-label">${R.esc(p)} priority</div></div>`).join('')}
      </div>
      ${!em.packagesCompleted.length ? '<p class="muted">No package has reached 100% human-asserted-complete yet — expected at this stage of the repository\'s life; see ROADMAP.md.</p>' : ''}
      <div class="stats-table-scroll"><table class="stats-table">
        <thead><tr><th>Package / item</th><th>Stage</th><th>Priority</th><th>Computed coverage</th><th>Source availability</th><th>Verification status</th><th>Est. effort</th></tr></thead>
        <tbody>${em.items.map((i) => `
          <tr>
            <td><strong>${R.esc(i.title)}</strong><div class="muted">${R.esc(i.package)}</div></td>
            <td>${stageBadge(i.stage)}</td>
            <td>${priorityBadge(i.priority)}</td>
            <td>${i.computedFacts ? i.computedFacts.avgCoveragePct + '% avg (' + i.computedFacts.standardCount + ' standards)' : '—'}</td>
            <td>${R.esc(i.sourceAvailability)}</td>
            <td>${R.esc(i.verificationStatus)}</td>
            <td>${R.esc(i.estimatedEffort)}</td>
          </tr>`).join('')}</tbody>
      </table></div>
    `;
  }

  // ---------- Amendment Tracker ----------
  function renderAmendmentTracker() {
    const container = document.getElementById('amendment-tracker-content');
    if (!container) return;
    const at = DB.getAmendmentTracker();
    if (!at) { container.innerHTML = '<p class="muted">index/amendment-tracker.json not found — run repository/build/amendment-tracker.js.</p>'; return; }

    const flagged = at.standards.filter((s) => s.pendingAmendments.length || s.staleStatusFlags.length || s.reviewOverdue);
    container.innerHTML = `
      <div class="stats-grid">
        <div class="stat-card"><div class="stat-value">${at.totalStandards}</div><div class="stat-label">Standards tracked</div></div>
        <div class="stat-card"><div class="stat-value">${at.withPendingAmendments}</div><div class="stat-label">With pending amendments</div></div>
        <div class="stat-card"><div class="stat-value">${at.withStaleStatusFlags}</div><div class="stat-label">Stale status flags</div></div>
        <div class="stat-card"><div class="stat-value">${at.overdueForReview}</div><div class="stat-label">Overdue for review</div></div>
      </div>
      <h4>Items needing attention (${flagged.length})</h4>
      ${flagged.length ? `<div class="stats-table-scroll"><table class="stats-table">
        <thead><tr><th>Standard</th><th>Current version</th><th>Last review</th><th>Next review due</th><th>Flags</th></tr></thead>
        <tbody>${flagged.map((s) => `
          <tr>
            <td><a href="#" class="xref exp-link" data-id="${R.esc(s.id)}">${R.esc(s.title)}</a></td>
            <td>${s.currentVersion ? 'v' + R.esc(s.currentVersion.version) + ' · ' + R.esc(s.currentVersion.effectiveFrom || '?') : '—'}</td>
            <td>${s.lastRepositoryReview ? R.esc(s.lastRepositoryReview.slice(0, 10)) : 'never logged'}</td>
            <td>${s.nextReviewRequired ? R.esc(s.nextReviewRequired) : '—'} ${s.reviewOverdue ? '<span class="ed-tag ed-fail">overdue</span>' : ''}</td>
            <td>${s.staleStatusFlags.map((f) => `<div class="muted">${R.esc(f.issue)}</div>`).join('')}${s.pendingAmendments.map((p) => `<div class="muted">Pending: v${R.esc(p.version)} effective ${R.esc(p.effectiveFrom)}</div>`).join('')}</td>
          </tr>`).join('')}</tbody>
      </table></div>` : '<p class="muted">Nothing currently flagged — no pending amendments, no stale status markers, nothing overdue for review.</p>'}
      <p class="muted" style="margin-top:10px;">Cadence policy: ${R.esc(at.cadencePolicy)}</p>
    `;
    container.querySelectorAll('.exp-link').forEach((a) => a.addEventListener('click', (e) => {
      e.preventDefault(); window.RulesNav.showTab('search'); R.showDetail(a.dataset.id);
    }));
  }

  // ---------- Repository Metrics (real growth trend) ----------
  function sparkline(values, width, height) {
    width = width || 240; height = height || 40;
    if (!values.length) return '';
    const max = Math.max(...values, 1);
    const min = Math.min(...values, 0);
    const range = Math.max(max - min, 1);
    const step = values.length > 1 ? width / (values.length - 1) : 0;
    const points = values.map((v, i) => `${Math.round(i * step)},${Math.round(height - ((v - min) / range) * height)}`).join(' ');
    return `<svg viewBox="0 0 ${width} ${height}" class="spark-svg" preserveAspectRatio="none"><polyline points="${points}" fill="none" stroke="var(--teal)" stroke-width="2"/></svg>`;
  }

  function renderMetrics() {
    const container = document.getElementById('metrics-content');
    if (!container) return;
    const mh = DB.getMetricsHistory();
    if (!mh || !mh.series.length) { container.innerHTML = '<p class="muted">index/metrics-history.json not found or empty — run repository/build/metrics-history.js.</p>'; return; }

    const series = mh.series;
    const metrics = [
      { key: 'standards', label: 'Standards' }, { key: 'nodes', label: 'Nodes' },
      { key: 'relationshipCount', label: 'Relationships' }, { key: 'definitions', label: 'Definitions' },
      { key: 'engineeringObjects', label: 'Engineering Objects' },
    ];
    container.innerHTML = `
      <p class="muted">${R.esc(mh.method)}</p>
      <div class="metrics-grid">
        ${metrics.map((m) => {
          const values = series.map((p) => p[m.key]).filter((v) => v !== null && v !== undefined);
          if (!values.length) return '';
          const first = values[0], last = values[values.length - 1];
          const growth = first ? Math.round(((last - first) / Math.max(first, 1)) * 100) : 0;
          return `<div class="metric-card">
            <div class="metric-label">${R.esc(m.label)}</div>
            <div class="metric-value">${last} <span class="metric-growth">${growth >= 0 ? '+' : ''}${growth}%</span></div>
            ${sparkline(values)}
            <div class="metric-range muted">${first} → ${last} across ${values.length} point(s)</div>
          </div>`;
        }).join('')}
      </div>
      <h4>Data points (${series.length})</h4>
      <div class="stats-table-scroll"><table class="stats-table">
        <thead><tr><th>Date</th><th>Commit</th><th>Standards</th><th>Nodes</th><th>Relationships</th><th>Definitions</th><th>EOs</th><th>Avg. coverage</th></tr></thead>
        <tbody>${series.map((p) => `<tr><td>${R.esc(p.date)}</td><td><code>${R.esc(p.commit)}</code></td><td>${p.standards}</td><td>${p.nodes}</td><td>${p.relationshipCount != null ? p.relationshipCount : '—'}</td><td>${p.definitions}</td><td>${p.engineeringObjects}</td><td>${p.avgCoveragePct != null ? p.avgCoveragePct + '%' : '—'}</td></tr>`).join('')}</tbody>
      </table></div>
    `;
  }

  function init() {
    renderManager();
    renderAmendmentTracker();
    renderMetrics();
  }

  return { init };
})();
