#!/usr/bin/env python3
"""Derive the cross-year recurrence and reuse map from the specs.

Usage: python tools/pastpapers/build_reuse_map.py [--check]

Writes meoclass1/pastpapers/docs/2025_2026_RECURRENCE_AND_REUSE_MAP.md.
With --check it writes nothing and fails if the file on disk is stale.

Why this is generated and not written by hand
---------------------------------------------
Every number here already lives in the specs: reuse_tier, reused_from,
question_delta, temporal_review, and the families recurrence_model.py computes
from the calendar. A hand-written map would be a second copy of that truth, and
the two would disagree the first time a question was reclassified. The repo has
one rule about this and it applies here: no duplicate truth. Re-run after any
spec change.

This module reads specs and writes one document. It never writes a spec.
"""
import argparse, collections, glob, io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from render_common import REPO_ROOT  # noqa: E402
import recurrence_model as RM  # noqa: E402

PP = os.path.join(REPO_ROOT, 'meoclass1', 'pastpapers')
OUT = os.path.join(PP, 'docs', '2025_2026_RECURRENCE_AND_REUSE_MAP.md')
YEAR = 2025


def load():
    specs = [json.load(open(p, encoding='utf-8'))
             for p in sorted(glob.glob(os.path.join(PP, 'specs', '*.json')))]
    nodes = RM.load_nodes(specs)
    return specs, nodes, RM.build_families(nodes)


def build():
    specs, nodes, rel = load()
    byq = {q['question_id']: (d, q) for d in specs for q in d['questions']}
    built = {qid for qid, (_, q) in byq.items() if q.get('model_answer')}
    q25 = sorted((n for n in nodes.values() if n['year'] == YEAR),
                 key=lambda n: (n['month_num'], int(n['q_no'][1:])))

    o = []
    a = o.append
    a('# 2025 <-> 2026 RECURRENCE AND REUSE MAP')
    a('')
    a('**Generated by `tools/pastpapers/build_reuse_map.py` from `specs/*.json`. Do not hand-edit.**')
    a('Re-run after any spec change; `--check` fails if this file is stale.')
    a('')
    a('Scope honesty: every count below is scoped to the sittings MIW has actually transcribed '
      '(2025 and 2026). A question with no relative here is **not** "never asked before"; it is '
      '"not repeated inside the set MIW has built". Adding 2024 will change these numbers, and '
      'nothing is cached to prevent that.')
    a('')

    # ---- 1 dataset
    tot = len(nodes)
    a('## 1. DATASET')
    a('')
    a('| | |')
    a('|---|---|')
    a('| Papers | %d (%d solved 2026, %d intake 2025) |'
      % (len(specs), sum(1 for d in specs if d['year'] == 2026),
         sum(1 for d in specs if d['year'] == YEAR)))
    a('| Questions | **%d** (%d built answers, %d questions only) |'
      % (tot, len(built), tot - len(built)))
    a('| Month absent from the available source set | **May**, in both years |')
    a('')

    # ---- 2 candidate-facing recurrence
    a('## 2. CHRONOLOGICAL RECURRENCE (candidate-facing)')
    a('')
    a('Computed in `recurrence_model.py` from `(year, month)` and nothing else. `recurrence_class` '
      'in the specs is an **authoring** field recorded in production order and is never rendered.')
    a('')
    c = collections.Counter(rel[n['question_id']]['status'] for n in q25)
    a('Across the 99 questions of 2025:')
    a('')
    a('| Status | Count | Meaning |')
    a('|---|---|---|')
    a('| First in set | %d | earliest sitting of a family that returns later |' % c['first'])
    a('| Repeated, same wording | %d | later sitting, stem identical to the first |' % c['repeat_exact'])
    a('| Repeated, reworded | %d | later sitting, stem materially reworded |' % c['repeat_near'])
    a('| Once in this set | %d | no relative anywhere in 2025 or 2026 |' % c['single'])
    a('')

    # ---- 3 families
    fam = collections.defaultdict(list)
    for n in nodes.values():
        fam[rel[n['question_id']]['family_id']].append(n['question_id'])
    multi = {k: v for k, v in fam.items() if len(v) > 1}
    cross = {k: v for k, v in multi.items()
             if len({nodes[m]['year'] for m in v}) > 1}
    a('## 3. QUESTION FAMILIES')
    a('')
    a('A family is a connected component over two undirected edge kinds: an adjudicated '
      '`reused_from` link, and equality of the normalised printed stem. Members are ordered by '
      'sitting date; the earliest names the family. **Nothing is cached in a spec**, so adding an '
      'older year re-derives every family and can demote a current "first occurrence" without any '
      'spec edit. That is the 2024-readiness guarantee.')
    a('')
    a('| | |')
    a('|---|---|')
    a('| Families total | %d |' % len(fam))
    a('| Multi-sitting families | %d |' % len(multi))
    a('| Of those, spanning both years | **%d** |' % len(cross))
    a('')
    a('### Multi-sitting families')
    a('')
    a('| Size | Span | Family | Sittings |')
    a('|---|---|---|---|')
    for fid, mem in sorted(multi.items(), key=lambda x: (-len(x[1]), x[0])):
        mem = sorted(mem, key=lambda m: (nodes[m]['year'], nodes[m]['month_num']))
        yrs = sorted({nodes[m]['year'] for m in mem})
        span = 'cross-year' if len(yrs) > 1 else str(yrs[0])
        chain = ' -> '.join('%s %s' % (nodes[m]['month_year'], nodes[m]['q_no']) for m in mem)
        a('| %d | %s | %s | %s |'
          % (len(mem), span, nodes[fid]['short_title'], chain))
    a('')

    # ---- 4 reuse tiers
    a('## 4. REUSE MAP')
    a('')
    tiers = collections.Counter(byq[n['question_id']][1].get('reuse_tier') for n in q25)
    a('| Tier | Count | Definition as applied |')
    a('|---|---|---|')
    a('| A | %d | Not assigned this session. |' % tiers['A'])
    a('| B | %d | Not assigned this session. |' % tiers['B'])
    a('| C | %d | No family member with a built answer. New research. |' % tiers['C'])
    a('| D | **%d** | Family contains a 2026 question whose answer is built and verified. |'
      % tiers['D'])
    a('')
    a('**Why A and B are zero, and why that is a finding rather than a gap.** Both tiers claim '
      'that an existing canonical object covers some or all of the examiner demand. That claim '
      'cannot be made without reading the object, and this session authors and verifies nothing. '
      'A keyword sweep of the 132-file Oral corpus was run and deliberately **not** used to assign '
      'B: no threshold produced a natural break (2 matching terms gave 91 hits, 3 gave 76, 4 gave '
      '49), so the signal is weak and any cut point would be arbitrary. A manufactured B count is '
      'worse than none, because it would be planned against. The sweep output is instead recorded '
      'per question in `reuse_evidence` as named candidate files to read, explicitly labelled '
      'discovery. **%d of the %d Tier C questions carry such candidates.** Promotion to A or B '
      'belongs to the solving session, which will have read them.'
      % (sum(1 for n in q25
             if any('ORAL-CORPUS CANDIDATES' in e
                    for e in (byq[n['question_id']][1].get('reuse_evidence') or []))),
         tiers['C']))
    a('')
    a('### Tier D in full — every 2025 question with a verified donor')
    a('')
    a('Direction matters and is easy to get backwards: **the 2025 sitting is the earlier one.** '
      'The donor is a later answer being pulled *backwards*, so any currency correction made for '
      'the later sitting must be reversed, not inherited.')
    a('')
    a('| 2025 question | Sitting | Donor | Wording | Temporal |')
    a('|---|---|---|---|---|')
    for n in q25:
        d, q = byq[n['question_id']]
        if q.get('reuse_tier') != 'D':
            continue
        donors = sorted(m for m in rel[n['question_id']]['others'] if m in built)
        same = any(nodes[m]['_stem'] == n['_stem'] for m in donors)
        tr = q.get('temporal_review') or {}
        a('| %s | %s %s | %s | %s | %s |'
          % (n['question_id'], n['month_year'], n['q_no'], ', '.join(donors),
             'identical' if same else 'reworded',
             '**%s**' % tr.get('risk') if tr.get('state') != 'STABLE' else 'stable'))
    a('')

    # ---- 5 temporal
    a('## 5. TEMPORAL REVIEW')
    a('')
    a('> **Every available 2025 sitting predates 15 March 2026**, when the Merchant Shipping Act, '
      '2025 commenced and repealed the 1958 Act by s.324(1).')
    a('')
    a('So the 2025 risk is the mirror image of the 2026 set\'s. Reusing a 2026 answer into a 2025 '
      'paper is a **statute regression**, not a re-anchor: the April 2026 sweep found the 1958 Act '
      'asserted on eight separate surfaces of a single question object — model answer, study '
      'guide, `recall_15s`, `major_trap`, an `answer_route` core point, a retrieval card, '
      '`regulations` and `search_aliases`. Expect eight again, in reverse.')
    a('')
    a('A 2025 answer must **not** be corrected to current law. It answers the examination as sat; '
      'the study guide is where the candidate is told the law has since changed.')
    a('')
    tr = [(n, (byq[n['question_id']][1].get('temporal_review') or {})) for n in q25]
    flagged = [(n, t) for n, t in tr if t.get('state') != 'STABLE']
    a('| | |')
    a('|---|---|')
    a('| Stable | %d |' % (len(tr) - len(flagged)))
    a('| Temporal review required | **%d** (HIGH %d, MEDIUM %d) |'
      % (len(flagged), sum(1 for _, t in flagged if t['risk'] == 'HIGH'),
         sum(1 for _, t in flagged if t['risk'] == 'MEDIUM')))
    a('')
    kinds = collections.Counter(k for _, t in flagged for k in t['classes'])
    a('| Risk class | Count |')
    a('|---|---|')
    for k, v in kinds.most_common():
        a('| %s | %d |' % (k, v))
    a('')
    a('### Flagged questions')
    a('')
    a('| Question | Sitting | Risk | Classes |')
    a('|---|---|---|---|')
    for n, t in flagged:
        a('| %s | %s %s | %s | %s |'
          % (n['question_id'], n['month_year'], n['q_no'], t['risk'], '; '.join(t['classes'])))
    a('')

    # ---- 6 production order
    a('## 6. RECOMMENDED SOLVING ORDER')
    a('')
    a('Not calendar order. Calendar order would research the same family several times and would '
      'meet the hardest temporal problem in the set on a paper chosen for its date rather than its '
      'readiness.')
    a('')
    paper_d = collections.Counter()
    paper_flag = collections.Counter()
    for n in q25:
        _, q = byq[n['question_id']]
        if q.get('reuse_tier') == 'D':
            paper_d[n['paper_id']] += 1
        if (q.get('temporal_review') or {}).get('state') != 'STABLE':
            paper_flag[n['paper_id']] += 1
    a('| Paper | Sitting | Tier D | Temporal flags |')
    a('|---|---|---|---|')
    for d in sorted((s for s in specs if s['year'] == YEAR), key=lambda s: -paper_d[s['paper_id']]):
        pid = d['paper_id']
        a('| %s | %s | **%d / 9** | %d |' % (pid, d['month_year'], paper_d[pid], paper_flag[pid]))
    a('')
    return '\n'.join(o) + '\n'


def build_inventory():
    """The governed source inventory. Also derived, for the same reason."""
    specs, nodes, _ = load()
    o = []
    a = o.append
    a('# 2025 SOURCE INVENTORY')
    a('')
    a('**Generated by `tools/pastpapers/build_reuse_map.py` from `specs/*.json`. Do not hand-edit.**')
    a('')
    a('## Availability')
    a('')
    months = {d['month'] for d in specs if d['year'] == YEAR}
    a('Eleven papers are held for 2025. **May is absent from the available MIW source set.** The '
      'source copies carry a printed serial that runs EM-2501 to EM-2504 and EM-2506 to EM-2512 '
      'with nothing at 2505, and May is likewise absent in 2026. That is recorded as source '
      'metadata, not as a finding about the examination calendar: MIW holds no official '
      'confirmation that no May sitting took place.')
    a('')
    a('| Paper | Month | Source file | Pages | Questions | Pages read back at 150 dpi |')
    a('|---|---|---|---|---|---|')
    for d in sorted((s for s in specs if s['year'] == YEAR), key=lambda s: s['paper_id']):
        tv = d['transcription_verified']['method']
        read = tv.split('Pages read back this session: ')[1].split(' of ')[0]
        a('| %s | %s | `%s` | %d | %d | %s |'
          % (d['paper_id'], d['month'], os.path.basename(d['source_copy_path']),
             d['source_copy_provenance']['pages'], len(d['questions']), read))
    a('')
    a('Source copies are **third-party, unverified**. No independently authoritative DG Shipping or '
      'MMD copy has been located or compared, so no 2025 paper may be described as an officially '
      'verified source. Host identity is recorded locally only, outside this public repository. '
      'The PDFs themselves are git-ignored by `.gitignore:42` and must be neither committed nor '
      'deleted.')
    a('')
    a('## Marks')
    a('')
    a('Every question is recorded at 16 marks under printed instruction 2 ("All questions carry '
      'equal marks"). Six answered questions therefore total 96 against a printed **Total Marks - '
      '100**. The discrepancy is printed on the source copy and is reproduced, not corrected.')
    a('')
    absent = [(d, q) for d in specs if d['year'] == YEAR
              for q in d['questions'] if q.get('printed_marks_absent')]
    a('### Questions printing NO mark allocation')
    a('')
    a('**%d of 99**, across %d papers. Each is recorded at 16 with `printed_marks_absent` set. '
      'The omission is the printed copy\'s, not a transcription loss: QP2506-Q9 prints no marks '
      'where the identical question printed (16) at the August sitting, and QP2511-Q4 prints none '
      'where the identical question printed (16) in December.'
      % (len(absent), len({d['paper_id'] for d, _ in absent})))
    a('')
    a('| Question | Sitting | Title |')
    a('|---|---|---|')
    for d, q in absent:
        a('| %s | %s %s | %s |' % (q['question_id'], d['month_year'], q['q_no'],
                                   q.get('short_title', '')))
    a('')
    a('## Recorded source anomalies')
    a('')
    a('Examiner wording is reproduced exactly, errors included. Each is recorded in a note so a '
      'future session does not read it as a transcription fault and "fix" it.')
    a('')
    a('| Question | Note |')
    a('|---|---|')
    for d in sorted((s for s in specs if s['year'] == YEAR), key=lambda s: s['paper_id']):
        for q in d['questions']:
            n = q.get('subpart_marks_note')
            if n and ('rint' in n or 'ANOMALY' in n or 'EDITORIAL' in n):
                a('| %s | %s |' % (q['question_id'], n.replace('|', '/')))
    a('')
    return '\n'.join(o) + '\n'


DOCS = [(OUT, build), (os.path.join(PP, 'docs', '2025_SOURCE_INVENTORY.md'), build_inventory)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='write nothing; fail if a file on disk is stale')
    args = ap.parse_args()
    stale = 0
    for path, fn in DOCS:
        body = fn()
        rel = os.path.relpath(path, REPO_ROOT)
        if args.check:
            cur = io.open(path, encoding='utf-8').read() if os.path.exists(path) else None
            if cur != body:
                print('STALE: %s does not match a fresh derivation from the specs. '
                      'Re-run without --check.' % rel)
                stale += 1
            continue
        with io.open(path, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(body)
        print('wrote %s' % rel)
    if args.check:
        if stale:
            sys.exit(1)
        print('reuse map and source inventory are current')


if __name__ == '__main__':
    main()
