#!/usr/bin/env python3
"""Derive the multi-year recurrence and reuse map from the specs.

Usage: python tools/pastpapers/build_reuse_map.py [--check]

Writes, into meoclass1/pastpapers/docs/:
    2024_2026_RECURRENCE_AND_REUSE_MAP.md   families, tiers, temporal risk, order
    SOURCE_INVENTORY.md                     what was transcribed, from what, how far

With --check it writes nothing and fails if either file on disk is stale.

Why this is generated and not written by hand
---------------------------------------------
Every number here already lives in the specs: reuse_tier, reused_from,
question_delta, temporal_review, and the families recurrence_model.py computes
from the calendar. A hand-written map would be a second copy of that truth, and
the two would disagree the first time a question was reclassified. The repo has
one rule about this and it applies here: no duplicate truth. Re-run after any
spec change.

Nothing in this module is year-specific. It reports whatever years have specs,
which is how the 2025<->2026 map became the 2024<->2026 map without being
rewritten a second time.

This module reads specs and writes two documents. It never writes a spec.
"""
import argparse, collections, glob, io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from render_common import REPO_ROOT  # noqa: E402
import recurrence_model as RM  # noqa: E402

PP = os.path.join(REPO_ROOT, 'meoclass1', 'pastpapers')
DOCS = os.path.join(PP, 'docs')


def load():
    specs = [json.load(open(p, encoding='utf-8'))
             for p in sorted(glob.glob(os.path.join(PP, 'specs', '*.json')))]
    nodes = RM.load_nodes(specs)
    return specs, nodes, RM.build_families(nodes)


def _years(specs):
    return sorted({d['year'] for d in specs})


def _solved_papers(specs):
    """Papers with every question built.

    This replaced _solved_years at the first paper-by-paper build. The old
    function returned every year containing ANY built answer, and the planning
    sections then skipped those years wholesale -- which was correct only while
    a year was either entirely solved or entirely untouched. Solving one 2025
    paper made 2025 a "solved year" and silently deleted the other ten 2025
    papers, and ninety unsolved questions, from the tier table, the temporal
    table and the recommended solving order. Exclusion is per PAPER.
    """
    return {d['paper_id'] for d in specs
            if all(q.get('model_answer') for q in d['questions'])}


def _open_years(specs, built):
    """Years that still contain at least one unsolved question."""
    return sorted({d['year'] for d in specs
                   for q in d['questions'] if q['question_id'] not in built})


def build():
    specs, nodes, rel = load()
    byq = {q['question_id']: (d, q) for d in specs for q in d['questions']}
    built = {qid for qid, (_, q) in byq.items() if q.get('model_answer')}
    years = _years(specs)
    solved_papers = _solved_papers(specs)
    open_years = _open_years(specs, built)
    unsolved = [n for n in nodes.values() if n['question_id'] not in built]

    # Donor readiness is DERIVED from the current built set, never read from the
    # stored intake tier. See recurrence_model.donor_readiness for why.
    ready = {qid: RM.donor_readiness(nodes, rel, built, qid) for qid in nodes}
    tier = {qid: RM.derive_reuse_tier(byq[qid][1].get('reuse_tier'),
                                      ready[qid]['donors']) for qid in nodes}
    drift = sorted((n for n in unsolved
                    if tier[n['question_id']] != byq[n['question_id']][1].get('reuse_tier')),
                   key=RM._sort_key)

    o = []
    a = o.append
    a('# %d &ndash; %d RECURRENCE AND REUSE MAP' % (years[0], years[-1]))
    a('')
    a('**Generated by `tools/pastpapers/build_reuse_map.py` from `specs/*.json`. Do not hand-edit.**')
    a('Re-run after any spec change; `--check` fails if this file is stale. This document '
      'supersedes `2025_2026_RECURRENCE_AND_REUSE_MAP.md`, which was the same derivation over a '
      'smaller corpus.')
    a('')
    a('Scope honesty: every count below is scoped to the sittings MIW has actually transcribed '
      '(%s). A question with no relative here is **not** "never asked before"; it is "not '
      'repeated inside the set MIW has built". Adding an older year will change these numbers, '
      'and nothing is cached to prevent that &mdash; adding %d moved **34** of the 153 previously '
      'transcribed questions.'
      % (', '.join(str(y) for y in years), years[0]))
    a('')

    # ---- 1 dataset
    a('## 1. DATASET')
    a('')
    a('| Year | Papers | Questions | Answers built |')
    a('|---|---|---|---|')
    for y in years:
        ps = [d for d in specs if d['year'] == y]
        qs = [n for n in nodes.values() if n['year'] == y]
        a('| %d | %d | %d | %d |'
          % (y, len(ps), len(qs), sum(1 for n in qs if n['question_id'] in built)))
    a('| **Total** | **%d** | **%d** | **%d** |' % (len(specs), len(nodes), len(built)))
    a('')
    a('Every paper sets nine questions and every question is recorded at 16 marks under printed '
      'instruction 2. **May is absent from the available MIW source set in all three years.**')
    a('')

    # ---- 2 candidate-facing recurrence
    a('## 2. CHRONOLOGICAL RECURRENCE (candidate-facing)')
    a('')
    a('Computed in `recurrence_model.py` from `(year, month)` and nothing else. The source copy '
      "host's printed annotation is discovery-only provenance held as `host_recurrence_hint` and "
      'never rendered; `recurrence_class` is an **authoring** field recorded in production order '
      'and never rendered. `recurrence_check.py` fails the build if either reaches a shipped '
      'surface.')
    a('')
    a('| Year | First in set | Repeated, same wording | Repeated, reworded | Once in this set |')
    a('|---|---|---|---|---|')
    for y in years:
        c = collections.Counter(rel[n['question_id']]['status']
                                for n in nodes.values() if n['year'] == y)
        a('| %d | %d | %d | %d | %d |'
          % (y, c['first'], c['repeat_exact'], c['repeat_near'], c['single']))
    a('')
    a('An earliest year cannot contain a "repeated, reworded" question that looks backwards, so '
      "%d's repeats are all internal to itself." % years[0])
    a('')

    # ---- 3 families
    fam = collections.defaultdict(list)
    for n in nodes.values():
        fam[rel[n['question_id']]['family_id']].append(n['question_id'])
    multi = {k: v for k, v in fam.items() if len(v) > 1}
    cross = {k: v for k, v in multi.items() if len({nodes[m]['year'] for m in v}) > 1}
    allthree = {k: v for k, v in multi.items()
                if len({nodes[m]['year'] for m in v}) == len(years)}
    a('## 3. QUESTION FAMILIES')
    a('')
    a('A family is a connected component over two undirected edge kinds: an adjudicated '
      '`reused_from` link marked `same_task`, and equality of the marks-normalised printed stem. '
      'Members are ordered by sitting date; the earliest names the family. **Nothing is cached in '
      'a spec**, so adding an older year re-derives every family and demotes a current "first '
      'occurrence" without any spec edit.')
    a('')
    a('| | |')
    a('|---|---|')
    a('| Families total | %d |' % len(fam))
    a('| Multi-sitting families | **%d** |' % len(multi))
    a('| Spanning more than one year | %d |' % len(cross))
    a('| Spanning all %d years | **%d** |' % (len(years), len(allthree)))
    a('')
    a('### Multi-sitting families, largest first')
    a('')
    a('| Size | Span | Family | Sittings |')
    a('|---|---|---|---|')
    for fid, mem in sorted(multi.items(),
                           key=lambda x: (-len(x[1]), RM._sort_key(nodes[x[0]]))):
        mem = sorted(mem, key=lambda m: RM._sort_key(nodes[m]))
        yrs = sorted({nodes[m]['year'] for m in mem})
        span = '&ndash;'.join(str(y) for y in (yrs[0], yrs[-1])) if len(yrs) > 1 else str(yrs[0])
        chain = ' &rarr; '.join('%s %s' % (nodes[m]['month_year'], nodes[m]['q_no']) for m in mem)
        a('| %d | %s | %s | %s |' % (len(mem), span, nodes[fid]['short_title'], chain))
    a('')

    # ---- 4 pairwise year relationships
    a('## 4. RELATIONSHIPS BY YEAR PAIR')
    a('')
    a('Every pair of questions inside one family, counted by the two sittings it joins. **EXACT** '
      'means the two marks-normalised stems are identical; **NEAR** means the same examiner task, '
      'materially reworded. Everything not in a family is **NONE**.')
    a('')
    a('**TOPIC is deliberately absent from this table and from the product.** A shared subject is '
      'not a repeated question, and rendering it as one is the single most misleading thing this '
      'page could do &mdash; the 2026 review found the host annotation making exactly that claim '
      'in both directions. Shared-subject browsing is served by `topics-<year>.html`, which is a '
      'routing surface and says nothing about recurrence.')
    a('')
    pair = collections.defaultdict(lambda: [0, 0])
    for mem in fam.values():
        mem = sorted(mem, key=lambda m: RM._sort_key(nodes[m]))
        for i in range(len(mem)):
            for j in range(i + 1, len(mem)):
                k = tuple(sorted((nodes[mem[i]]['year'], nodes[mem[j]]['year'])))
                same = nodes[mem[i]]['_stem'] == nodes[mem[j]]['_stem']
                pair[k][0 if same else 1] += 1
    a('| Year pair | EXACT | NEAR | Total edges |')
    a('|---|---|---|---|')
    for k in sorted(pair):
        e, nr = pair[k]
        label = '%d internal' % k[0] if k[0] == k[1] else '%d &harr; %d' % k
        a('| %s | %d | %d | %d |' % (label, e, nr, e + nr))
    tot = [sum(v[0] for v in pair.values()), sum(v[1] for v in pair.values())]
    a('| **All pairs** | **%d** | **%d** | **%d** |' % (tot[0], tot[1], tot[0] + tot[1]))
    a('')

    # ---- 5 reuse tiers
    a('## 5. REUSE MAP')
    a('')
    a('**Tiers C and D below are DERIVED from the current built set on every run, not read from '
      'the stored `reuse_tier` field.** The stored field is intake metadata: it records what was '
      'true when the question was transcribed and it does not move when a sibling paper is '
      'solved. Planning off it means planning off the past. Section 5.1 records exactly what that '
      'drift currently costs.')
    a('')
    a('| Tier | %s | Definition as applied |' % ' | '.join(str(y) for y in open_years))
    a('|' + '---|' * (len(open_years) + 2))
    for t, why in (('A', 'Carried from the adjudicated intake field. An existing canonical object '
                         'fully covers the demand.'),
                   ('B', 'Carried from the adjudicated intake field. An existing canonical object '
                         'partly covers the demand.'),
                   ('C', 'Derived: no family member has a built answer. New research.'),
                   ('D', 'Derived: the family contains at least one question whose answer is '
                         'built and verified.')):
        # Count UNSOLVED questions only. A tier is a statement about work still
        # to do, so a solved question inside a part-solved year must not be
        # counted against it.
        counts = [sum(1 for n in unsolved if n['year'] == y and tier[n['question_id']] == t)
                  for y in open_years]
        a('| %s | %s | %s |' % (t, ' | '.join('**%d**' % c if t == 'D' else str(c)
                                              for c in counts), why))
    a('')
    a('**Why A and B are still zero, and why that is a finding rather than a gap.** Both tiers '
      'claim that an existing canonical object covers some or all of the examiner demand. That '
      'claim cannot be made without reading the object, and this session authors and verifies '
      'nothing. A keyword sweep of the Oral corpus was run for the 2025 intake and deliberately '
      '**not** used to assign B: no threshold produced a natural break, so any cut point would be '
      'arbitrary, and a manufactured B count is worse than none because it would be planned '
      'against. That sweep output survives per question in `reuse_evidence` as named candidate '
      'files to read, explicitly labelled discovery. Promotion to A or B belongs to the solving '
      'session, which will have read them.')
    a('')
    a('### 5.1 Derived tier against stored intake tier')
    a('')
    a('Every unsolved question whose CURRENT readiness differs from the tier frozen at intake. '
      'Each row is a question that acquired a verified donor because some other paper was solved '
      'after this question was transcribed. **Nothing in any spec changed to produce this table** '
      '&mdash; that is the point of deriving it.')
    a('')
    if drift:
        a('| Question | Sitting | Stored | Derived | Donor that arrived |')
        a('|---|---|---|---|---|')
        for n in drift:
            qid = n['question_id']
            a('| %s | %s %s | %s | **%s** | %s |'
              % (qid, n['month_year'], n['q_no'],
                 byq[qid][1].get('reuse_tier') or '&mdash;', tier[qid],
                 ', '.join(ready[qid]['donors']) or '&mdash;'))
        a('')
        a('Stored Tier D over the unsolved set counts **%d**; derived counts **%d**. Planning off '
          'the stored field would have under-counted ready work by %d question(s) and would have '
          'sent a solving session to research answers that already have a verified donor.'
          % (sum(1 for n in unsolved if byq[n['question_id']][1].get('reuse_tier') == 'D'),
             sum(1 for n in unsolved if tier[n['question_id']] == 'D'), len(drift)))
    else:
        a('None. Every unsolved question\'s stored tier currently agrees with its derived '
          'readiness. This table is expected to repopulate as soon as the next paper is solved.')
    a('')
    a('### Tier D in full &mdash; every unsolved question with a verified donor')
    a('')
    a('Direction matters and is easy to get backwards: **the unsolved sitting is the earlier '
      'one.** The donor is a later answer being pulled *backwards*, so any currency correction '
      'made for the later sitting must be reversed, not inherited.')
    a('')
    a('`Preferred` is one donor selected deterministically from the family: an EXACT printed stem '
      'first, then the nearest sitting, then question id. It is a starting point for the solving '
      'session, not an instruction &mdash; **the target question always owns its own answer**, and '
      'every other donor in the row remains available.')
    a('')
    a('| Question | Sitting | Preferred | Wording | Other donors | Temporal |')
    a('|---|---|---|---|---|---|')
    for n in sorted(unsolved, key=RM._sort_key):
        qid = n['question_id']
        if tier[qid] != 'D':
            continue
        q = byq[qid][1]
        r = ready[qid]
        tr = q.get('temporal_review') or {}
        rest = [m for m in r['donors'] if m != r['preferred']]
        a('| %s | %s %s | %s | %s | %s | %s |'
          % (qid, n['month_year'], n['q_no'], r['preferred'],
             'identical' if r['exact'] else 'reworded', ', '.join(rest) or '&mdash;',
             '**%s**' % tr.get('risk') if tr.get('state') != 'STABLE' else 'stable'))
    a('')

    # ---- 6 temporal
    a('## 6. TEMPORAL REVIEW')
    a('')
    a('> **Every available %d and %d sitting predates 15 March 2026**, when the Merchant Shipping '
      'Act, 2025 commenced and repealed the 1958 Act by s.324(1).' % (years[0], years[1]))
    a('')
    a('So the risk on the unsolved papers is the mirror image of the 2026 set\'s. Reusing a 2026 '
      'answer into an earlier paper is a **statute regression**, not a re-anchor: the April 2026 '
      'sweep found the 1958 Act asserted on eight separate surfaces of a single question object '
      '&mdash; model answer, study guide, `recall_15s`, `major_trap`, an `answer_route` core '
      'point, a retrieval card, `regulations` and `search_aliases`. Expect eight again, in '
      'reverse.')
    a('')
    a('An earlier answer must **not** be corrected to current law. It answers the examination as '
      'sat; the study guide is where the candidate is told the law has since changed.')
    a('')
    tr = [(n, (byq[n['question_id']][1].get('temporal_review') or {})) for n in unsolved]
    flagged = [(n, t) for n, t in tr if t.get('state') != 'STABLE']
    a('| Year | Stable | Review required | HIGH | MEDIUM |')
    a('|---|---|---|---|---|')
    for y in open_years:
        yf = [(n, t) for n, t in flagged if n['year'] == y]
        yt = [(n, t) for n, t in tr if n['year'] == y]
        a('| %d | %d | **%d** | %d | %d |'
          % (y, len(yt) - len(yf), len(yf),
             sum(1 for _, t in yf if t['risk'] == 'HIGH'),
             sum(1 for _, t in yf if t['risk'] == 'MEDIUM')))
    a('| **Total** | %d | **%d** | %d | %d |'
      % (len(tr) - len(flagged), len(flagged),
         sum(1 for _, t in flagged if t['risk'] == 'HIGH'),
         sum(1 for _, t in flagged if t['risk'] == 'MEDIUM')))
    a('')
    kinds = collections.Counter(k for _, t in flagged for k in t['classes'])
    a('| Risk class | Count |')
    a('|---|---|')
    for k, v in kinds.most_common():
        a('| %s | %d |' % (k, v))
    a('')
    a('### Flagged questions')
    a('')
    a('| Question | Sitting | Risk | Classes |')
    a('|---|---|---|---|')
    for n, t in sorted(flagged, key=lambda x: RM._sort_key(x[0])):
        a('| %s | %s %s | %s | %s |'
          % (n['question_id'], n['month_year'], n['q_no'], t['risk'], '; '.join(t['classes'])))
    a('')

    # ---- 7 production order
    a('## 7. RECOMMENDED SOLVING ORDER')
    a('')
    a('Not calendar order. Calendar order would research the same family several times and would '
      'meet the hardest temporal problem in the set on a paper chosen for its date rather than '
      'its readiness.')
    a('')
    a('`Tier D` is how many of the nine questions already have a verified donor, **derived from '
      'the current built set** (§5.1). `Family reach` is how many OTHER unsolved questions across '
      'the whole corpus sit in the same families as this paper\'s questions &mdash; the research '
      'this paper converts for free elsewhere.')
    a('')
    rows = []
    for d in specs:
        if d['paper_id'] in solved_papers:
            continue
        pid = d['paper_id']
        qs = [q['question_id'] for q in d['questions']]
        dcount = sum(1 for q in d['questions'] if tier[q['question_id']] == 'D')
        flags = sum(1 for q in d['questions']
                    if (q.get('temporal_review') or {}).get('state') != 'STABLE')
        reach = len({m for q in qs for m in rel[q]['others']
                     if m not in built and m not in qs})
        rows.append((dcount, reach, pid, d['month_year'], flags))
    a('| Paper | Sitting | Tier D | Family reach | Temporal flags |')
    a('|---|---|---|---|---|')
    for dcount, reach, pid, my, flags in sorted(rows, key=lambda r: (-r[0], -r[1], r[2])):
        a('| %s | %s | **%d / 9** | %d | %d |' % (pid, my, dcount, reach, flags))
    a('')

    # ---- 8 written study intelligence
    a('## 8. WRITTEN STUDY INTELLIGENCE')
    a('')
    a('Evidence for a future Written study product. **No prediction of future examination '
      'questions is made or implied**; every statement is of the form "appeared in X available '
      'sittings".')
    a('')
    a('### Families by number of available sittings')
    a('')
    hist = collections.Counter(len(v) for v in fam.values())
    a('| Sittings | Families |')
    a('|---|---|')
    for k in sorted(hist, reverse=True):
        a('| %d | %d |' % (k, hist[k]))
    a('')
    a('### Families appearing in every available year')
    a('')
    if allthree:
        a('| Family | Sittings |')
        a('|---|---|')
        for fid, mem in sorted(allthree.items(), key=lambda x: -len(x[1])):
            mem = sorted(mem, key=lambda m: RM._sort_key(nodes[m]))
            a('| %s | %s |' % (nodes[fid]['short_title'],
                               ', '.join('%s %s' % (nodes[m]['month_year'], nodes[m]['q_no'])
                                         for m in mem)))
    else:
        a('None.')
    a('')
    a('### Category weight across the corpus')
    a('')
    cats = collections.Counter(n['primary_category'] for n in nodes.values())
    catfam = collections.Counter(nodes[k]['primary_category'] for k in fam)
    a('| Category | Questions | Distinct families |')
    a('|---|---|---|')
    for c, v in cats.most_common():
        a('| %s | %d | %d |' % (c, v, catfam[c]))
    a('')
    a('The ratio of the two columns is the study-material signal: a category with many questions '
      'and few families is one where a single verified engineering base serves several sittings. '
      'A category where the two numbers are close is one where each sitting asked something '
      'genuinely different.')
    a('')
    return '\n'.join(o) + '\n'


def build_inventory():
    """The governed source inventory. Also derived, for the same reason."""
    specs, nodes, _ = load()
    years = _years(specs)
    o = []
    a = o.append
    a('# WRITTEN QUESTION PAPERS &mdash; SOURCE INVENTORY')
    a('')
    a('**Generated by `tools/pastpapers/build_reuse_map.py` from `specs/*.json`. Do not '
      'hand-edit.** Supersedes `2025_SOURCE_INVENTORY.md`.')
    a('')
    a('## Availability')
    a('')
    a('| Year | Papers held | Months absent from the available source set |')
    a('|---|---|---|')
    MONTHS = list(RM.MONTHS)
    for y in years:
        held = {d['month'] for d in specs if d['year'] == y}
        a('| %d | %d | %s |' % (y, len(held),
                                ', '.join(m for m in MONTHS if m not in held) or 'none'))
    a('')
    a('**May is absent in all three years.** The printed serials support that as a fact about the '
      'source set rather than merely about MIW\'s backlog: the 2024 serials run &hellip;2404, '
      '2406&hellip; and the 2025 serials run &hellip;2504, 2506&hellip;, with nothing at 2405 or '
      '2505. It is still recorded as source metadata, not as a finding about the examination '
      'calendar: MIW holds no official confirmation that no May sitting took place.')
    a('')
    a('| Paper | Sitting | Source file | Printed serial | Pages | Questions | Pages read back |')
    a('|---|---|---|---|---|---|---|')
    for d in sorted(specs, key=lambda s: s['paper_id']):
        tv = d['transcription_verified']['method']
        read = tv.split('Pages read back this session: ')[1].split(' of ')[0] \
            if 'Pages read back this session: ' in tv else '?'
        p = d['source_copy_provenance']
        a('| %s | %s | `%s` | %s | %d | %d | %s of %d |'
          % (d['paper_id'], d['month_year'], os.path.basename(d['source_copy_path']),
             p.get('printed_serial', '&mdash;'), p['pages'], len(d['questions']),
             read, p['pages']))
    a('')
    a('Source copies are **third-party, unverified**. No independently authoritative DG Shipping '
      'or MMD copy has been located or compared, so no paper may be described as an officially '
      'verified source. Host identity is recorded locally only, outside this public repository. '
      'The PDFs themselves are git-ignored by `.gitignore:42` and must be neither committed nor '
      'deleted.')
    a('')
    a('### A note on the 2024 serial numbers')
    a('')
    a('The 2025 and 2026 copies print a four-digit serial that encodes the sitting (`EM - 2509` '
      'is September 2025). Three of the 2024 copies do not: January prints `EM - 24117-1`, '
      'February `EM - 19224-1` and March `EM - 18324-1`, none of which decode to their own month. '
      'April onwards reverts to the four-digit form. The serial is recorded exactly as printed '
      'and **is not used to identify a paper**; the month printed at the head of each copy is.')
    a('')
    a('## Marks')
    a('')
    a('Every question is recorded at 16 marks under printed instruction 2 ("All questions carry '
      'equal marks"). Six answered questions therefore total 96 against a printed **Total Marks '
      '- 100**. The discrepancy is printed on the source copy and is reproduced, not corrected.')
    a('')
    absent = [(d, q) for d in specs for q in d['questions'] if q.get('printed_marks_absent')]
    a('### Questions printing NO mark allocation')
    a('')
    a('**%d of %d**, across %d papers. Each is recorded at 16 with `printed_marks_absent` set. '
      'The omission is the printed copy\'s, not a transcription loss, and the corpus proves it '
      'twice over: `QP2506-Q9` prints no marks where the identical question printed (16) in '
      'August, and `QP2511-Q4` prints none where the identical question printed (16) in December.'
      % (len(absent), len(nodes), len({d['paper_id'] for d, _ in absent})))
    a('')
    a('| Question | Sitting | Title |')
    a('|---|---|---|')
    for d, q in absent:
        a('| %s | %s %s | %s |' % (q['question_id'], d['month_year'], q['q_no'],
                                   q.get('short_title', '')))
    a('')
    a('Printed marks are **metadata, not examiner wording**. `recurrence_model.normalise_stem` '
      'removes a marks token before comparing two stems, so the same task set once with a '
      'printed (16) and once without is EXACT rather than "reworded". Three real pairs in this '
      'corpus turn on exactly that, and the guard against over-stripping is tested in '
      '`recurrence_check.py`.')
    a('')
    a('## Recorded source anomalies')
    a('')
    a('Examiner wording is reproduced exactly, errors included. Each is recorded in a note so a '
      'future session does not read it as a transcription fault and "fix" it.')
    a('')
    a('| Question | Note |')
    a('|---|---|')
    for d in sorted(specs, key=lambda s: s['paper_id']):
        for q in d['questions']:
            n = q.get('subpart_marks_note')
            if n and ('rint' in n or 'ANOMALY' in n or 'EDITORIAL' in n or 'encode' in n):
                a('| %s | %s |' % (q['question_id'], n.replace('|', '/')))
    a('')
    return '\n'.join(o) + '\n'


DOCUMENTS = [
    (os.path.join(DOCS, '2024_2026_RECURRENCE_AND_REUSE_MAP.md'), build),
    (os.path.join(DOCS, 'SOURCE_INVENTORY.md'), build_inventory),
]

# Files this module used to generate over a smaller corpus. Leaving them on disk
# would leave two generated documents making different current claims, which is
# the duplicate-truth failure this module exists to avoid.
SUPERSEDED = [os.path.join(DOCS, '2025_2026_RECURRENCE_AND_REUSE_MAP.md'),
              os.path.join(DOCS, '2025_SOURCE_INVENTORY.md')]


def self_test():
    """Positive-control the donor-readiness derivation. Writes nothing.

    A check that only ever reads the real corpus cannot tell the difference
    between "derived correctly" and "read a stored field that happens to
    agree". Every case below therefore MUTATES the built set and asserts the
    tier moves with it. If any of these pass while the classifier is reading
    frozen intake metadata, the test is worthless -- so case 1 and case 2 are
    written to fail loudly in exactly that situation.
    """
    specs, nodes, rel = load()
    byq = {q['question_id']: (d, q) for d in specs for q in d['questions']}
    built = {qid for qid, (_, q) in byq.items() if q.get('model_answer')}
    fails = []

    def check(label, ok, detail=''):
        print('  %-4s %s%s' % ('PASS' if ok else 'FAIL', label,
                               '' if ok else '  -- %s' % detail))
        if not ok:
            fails.append(label)

    def tier_of(qid, b):
        r = RM.donor_readiness(nodes, rel, b, qid)
        return RM.derive_reuse_tier(byq[qid][1].get('reuse_tier'), r['donors']), r

    unsolved = [n['question_id'] for n in nodes.values() if n['question_id'] not in built]

    # ---- case 1: solving a donor must CREATE a tier D (C -> D)
    # A stored-field classifier cannot move here, because no spec is touched.
    cand = next((q for q in sorted(unsolved)
                 if not [m for m in rel[q]['others'] if m in built] and rel[q]['others']), None)
    if cand is None:
        check('case 1 C->D on donor arrival', False, 'no unsolved question with an unsolved family')
    else:
        sibling = sorted(rel[cand]['others'])[0]
        before, _ = tier_of(cand, built)
        after, r = tier_of(cand, built | {sibling})
        check('case 1 C->D when %s is solved (%s)' % (sibling, cand),
              before == 'C' and after == 'D' and r['preferred'] == sibling,
              'before=%s after=%s preferred=%s' % (before, after, r['preferred']))

    # ---- case 2: un-solving every donor must DESTROY a tier D (D -> C)
    cand2 = next((q for q in sorted(unsolved)
                  if [m for m in rel[q]['others'] if m in built]), None)
    if cand2 is None:
        check('case 2 D->C on donor loss', False, 'no unsolved question currently has a donor')
    else:
        donors = {m for m in rel[cand2]['others'] if m in built}
        before, r0 = tier_of(cand2, built)
        after, r1 = tier_of(cand2, built - donors)
        check('case 2 D->C when %s un-built (%s)' % (','.join(sorted(donors)), cand2),
              before == 'D' and after == 'C'
              and r0['preferred'] in donors and r1['preferred'] is None,
              'before=%s after=%s' % (before, after))

    # ---- case 3: family membership alone must NOT create a donor
    # This is the "recurrence family is not a preferred donor" boundary.
    fam_only = [q for q in unsolved if rel[q]['others']
                and not [m for m in rel[q]['others'] if m in built]]
    check('case 3 unsolved family members are not donors (%d question(s))' % len(fam_only),
          all(tier_of(q, built)[0] == 'C' and tier_of(q, built)[1]['preferred'] is None
              for q in fam_only))

    # ---- case 4: preferred donor prefers EXACT wording over a nearer sitting
    # QP2509-Q3 (September 2025) has three donors: QP2601-Q3 and QP2604-Q3 are
    # reworded and nearer; QP2607-Q5 is an identical printed stem and further
    # away. The identical stem must win.
    if 'QP2509-Q3' in nodes:
        _, r = tier_of('QP2509-Q3', built)
        check('case 4 EXACT donor beats a nearer reworded one (QP2509-Q3)',
              r['preferred'] == 'QP2607-Q5' and r['exact'] is True,
              'preferred=%s exact=%s donors=%s' % (r['preferred'], r['exact'], r['donors']))

    # ---- case 5: among equally EXACT donors, the nearest sitting wins
    # QP2509-Q2 (September 2025) has two identical-stem donors: QP2508-Q2 is one
    # month earlier, QP2602-Q2 is five months later. The one-month donor wins.
    if 'QP2509-Q2' in nodes:
        _, r = tier_of('QP2509-Q2', built)
        check('case 5 nearest sitting breaks an EXACT tie (QP2509-Q2)',
              r['preferred'] == 'QP2508-Q2' and r['exact'] is True,
              'preferred=%s donors=%s' % (r['preferred'], r['donors']))

    # ---- case 6: derivation must never LOSE a stored D that still has a donor
    lost = [q for q in unsolved if byq[q][1].get('reuse_tier') == 'D'
            and tier_of(q, built)[0] != 'D']
    check('case 6 no stored tier D with a live donor is demoted', not lost, ', '.join(lost))

    # ---- case 7: the regression itself -- stored and derived must be allowed
    # to disagree, and every disagreement must be explained by a real donor.
    drift = [q for q in unsolved if tier_of(q, built)[0] != byq[q][1].get('reuse_tier')]
    unexplained = [q for q in drift if not tier_of(q, built)[1]['donors']
                   and byq[q][1].get('reuse_tier') not in ('A', 'B')]
    print('  INFO stored-vs-derived drift: %d unsolved question(s)%s'
          % (len(drift), ': ' + ', '.join(sorted(drift)) if drift else ''))
    check('case 7 every drift row is explained by a built donor', not unexplained,
          ', '.join(unexplained))

    print('reuse map self-test: %s' % ('PASS' if not fails else 'FAIL (%d)' % len(fails)))
    return 1 if fails else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='write nothing; fail if a file on disk is stale')
    ap.add_argument('--self-test', action='store_true',
                    help='positive-control the donor-readiness derivation; writes nothing')
    args = ap.parse_args()
    if args.self_test:
        sys.exit(self_test())
    stale = 0
    for path, fn in DOCUMENTS:
        body = fn()
        rel = os.path.relpath(path, REPO_ROOT)
        if args.check:
            cur = io.open(path, encoding='utf-8').read() if os.path.exists(path) else None
            if cur != body:
                print('STALE: %s does not match a fresh derivation from the specs. '
                      'Re-run without --check.' % rel)
                stale += 1
            continue
        with io.open(path, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(body)
        print('wrote %s' % rel)
    for path in SUPERSEDED:
        rel = os.path.relpath(path, REPO_ROOT)
        if not os.path.exists(path):
            continue
        if args.check:
            print('STALE: %s is superseded and must be deleted. Re-run without --check.' % rel)
            stale += 1
        else:
            os.remove(path)
            print('removed %s (superseded)' % rel)
    if args.check:
        if stale:
            sys.exit(1)
        print('reuse map and source inventory are current')


if __name__ == '__main__':
    main()
